#define HIWI_FRAME_START 0xBD
#define HIWI_FRAME_END 0xDB
#define HIWI_RESPONSE_MT 0x0
#define HIWI_COMMAND_MT 0x1
#define HIWI_QUERY_MT 0x2
#define HIWI_BROADCAST_MT 0xF
#define HIWI_LOCKED_OPCODE 0x0
#define HIWI_PRIVACY_OPCODE 0x1
#define HIWI_1_WIRE_OPCODE 0x2
#define HIWI_FAILED_LOGINS_OPCODE 0x3
#define HIWI_INVALID_LOGIN_OPCODE 0x4

int query_state();
int set_state();
